# 2025/8/8 灰階圖片展現

In [2]:
from PIL import Image
import numpy as np
import matplotlib.pyplot as plt

In [3]:
s = [
        [157,153,174,168,150,152,129,151,172,161,156,156],
        [155,182,163, 74, 76, 62, 33, 17,110,210,180,154],
        [180,180, 50, 14, 34,  6, 10, 33, 48,106,150,181],
        [206,109,  5,124,131,111,120,204,166, 15, 56,180],
        [194, 64,137,251,237,239,210,220,227, 87, 71,201],
        [172,106,207,233,233,214,220,239,228, 98, 74,206],
        [198, 84,179,209,116,215,211,158,119, 75, 10,169],
        [199, 97,166, 84, 10,168,134, 11, 31, 62, 22,148],
        [199,168,191,193,158,227,178,143,182,106, 36,190],
        [206,174,156,252,216,231,140,178,228, 43, 96,234],
        [190,216,116,149,236,187, 86,150, 79, 38,218,241],
        [190,224,147,100,227,210,127,102, 36,101,255,224],
        [190,214,173, 66,103,143, 96, 50,  2,109,249,215],
        [187,196,236, 75,  1, 81, 47,000,  6,217,255,211],
        [183,202,237,145,  0,  0, 12,108,200,138,243,236],
        [196,206,123,207,177,121,123,200,176, 13, 96,218] ]

In [13]:
# 轉換成 numpy array ，並指為uint-8 類型(0-255))
arr = np.array(s, dtype=np.uint8)

img = Image.fromarray(arr)
img.show() # 另外產生圖片在電腦上而不是直接輸出在notebook上

In [6]:
# 轉成 numpy 陣列，並指為uint-8 類型(0-255))
arr = np.array(s, dtype=np.uint8)

# 顯示灰階圖片
plt.imshow(arr, cmap='gray', vmin=0, vmax=255)
plt.title("Grayscale Image")
plt.colorbar()  # 可選，顯示右側色階
plt.show()

In [7]:
arr = np.array(s,np.uint8)

In [8]:
arr.shape

(16, 12)

In [9]:
a1=arr[2:14,2:10]

In [10]:
print(a1)

[[ 50  14  34   6  10  33  48 106]
 [  5 124 131 111 120 204 166  15]
 [137 251 237 239 210 220 227  87]
 [207 233 233 214 220 239 228  98]
 [179 209 116 215 211 158 119  75]
 [166  84  10 168 134  11  31  62]
 [191 193 158 227 178 143 182 106]
 [156 252 216 231 140 178 228  43]
 [116 149 236 187  86 150  79  38]
 [147 100 227 210 127 102  36 101]
 [173  66 103 143  96  50   2 109]
 [236  75   1  81  47   0   6 217]]


In [11]:
s1 = s [2:14]
s2 = list(zip(*s1))
s3 = s2 [2:10]
s4 = list(zip(*s3))

In [12]:
# 顯示灰階圖片
plt.imshow(a1, cmap='gray', vmin=0, vmax=255)
plt.title("Grayscale Image")
plt.colorbar()  # 可選，顯示右側色階
plt.show()